### ISSUE TITLE
FR.9 Calendar view feature - Month display

### ISSUE THREAD

**Issue by fx0285** [WSU-4110/College-Events-Calendar-#10]
| FR.9 Calendar view feature - Month display |
|--|
|**Goal**: The current month is displayed, allowing the user to choose any day to expand into
**Stakeholders:** Students, organizers  |
| **Description:** The initial display of the calendar will be the month view and the user will have the option of clicking any day of the month, which will lead the Day display, listing all the events happening that day (FR10).  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |
|**Version:** 1.0 |
|**Date:** 01/11/2020
| **Priority:** 1 |

**Comment by JHuraibi** [comment]
[UseCase_5.docx](https://github.com/WSU-4110/College-Events-Calendar-/files/4196438/UseCase_5.docx)

**Comment by JHuraibi** [comment]
Feature implemented.
