### ISSUE TITLE
FR.14 Indicate when event has ended - event view page by day

### ISSUE THREAD

**Issue by fx0285** [WSU-4110/College-Events-Calendar-#14]
| FR.14 Indicate when event has ended - event view page by day |
|--|
|**Goal**: Indicate on the day view event page when an event is over with a visual transition
**Stakeholders:** Students |
| **Description:** To help users navigate the event view page the app will transition the appearance of events that have passed.  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |
|**Version:** 1.0 |
|**Date:** 01/11/2020
| **Priority:** 5 |

**Comment by JHuraibi** [comment]
Completed. For code, see "EventIndicators/wip" branch.
