### ISSUE TITLE
FR.8 Full Display View of event 

### ISSUE THREAD

**Issue by fx0285** [WSU-4110/College-Events-Calendar-#9]
| FR.8 Full Display View of event |
|--|
|**Goal**: Clicking on an event in the calendar opens up another page with the full description of the event
**Stakeholders:** Students, organizers  |
| **Description:** If a student is looking at the calendar and sees a title of an event they are interested in, they can click on the event, which opens up a page with the full description of the event, created by the organizer. This page would contain the Title, Organizer, Description, Location, Time, Tags and Cost.  |
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting. |
|**Version:** 1.0 |
|**Date:** 01/11/2020
| **Priority:** 2 |

**Comment by JHuraibi** [comment]
Feature Implemented (MODIFIED). 
Original Proposed Flow: [ Month View -> Full Display View of Event ]
Implemented Flow: [ Month View -> Events List -> Full Display View of Event ]
